import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Health from "../component/Health";
import Service from "../component/Service";
import Treatment from "../component/Treatment";
import Appointment from "../component/Appointment";
import FAQ from "../component/FAQ";
import Testimonial from "../component/Testimonial";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Health Bondhu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Health />
      <Service />
      <Treatment />
      <Appointment />
      <FAQ />
      <Testimonial/>
    </div>
  );
}
